smtp:
  host: smtp.strato.de
  port: 587
  use_tls: true
  username: rapporten@ronnyhullegie.nl
email:
  from_name: EMSN Vogelmonitoring
  from_address: rapporten@ronnyhullegie.nl
  admin_email: ronny@ronnyhullegie.nl
recipients:
- email: rapporten@ronnyhullegie.nl
  name: Ronny Hullegie
  mode: auto
  style: wetenschappelijk
  report_types:
  - weekly
  - monthly
  - seasonal
  - yearly
- email: peterkappers@hotmail.nl
  name: Peter
  mode: auto
  style: populair
  report_types:
  - weekly
  - monthly
  - seasonal
  - yearly
- email: moniqueoorsprong@outlook.com
  name: Monique
  mode: manual
  style: populair
  report_types:
  - weekly
  - monthly
  - seasonal
  - yearly
- email: info@vogelwerkgroepmiddenoverijssel.nl
  name: VWGMO
  mode: auto
  style: wetenschappelijk
  report_types:
  - seasonal
- email: aterborg80@gmail.com
  name: Alethea
  mode: auto
  style: populair
  report_types:
  - monthly
reports:
  auto_send:
    weekly: true
    monthly: true
    seasonal: true
    yearly: true
  subjects:
    weekly: EMSN Weekrapport {week} - {year}
    monthly: EMSN Maandrapport {month} {year}
    seasonal: EMSN Seizoensrapport {season} {year}
    yearly: EMSN Jaaroverzicht {year}
